import type { CountryProfile } from "@/types/passport";

// City choices are intentionally kept in the UI layer. Visa rules stay keyed by
// country, while this list lets a traveller make the itinerary feel personal.
const cityMap: Record<string, string[]> = {
  AFG: ["Kabul", "Herat"],
  ALB: ["Tirana", "Durres"],
  ARE: ["Dubai", "Abu Dhabi", "Sharjah"],
  ARG: ["Buenos Aires", "Cordoba", "Mendoza"],
  ARM: ["Yerevan", "Gyumri"],
  AUS: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
  AUT: ["Vienna", "Salzburg", "Innsbruck"],
  AZE: ["Baku", "Ganja"],
  BEL: ["Brussels", "Antwerp", "Bruges"],
  BGD: ["Dhaka", "Chattogram", "Sylhet"],
  BGR: ["Sofia", "Varna", "Plovdiv"],
  BHR: ["Manama", "Riffa"],
  BOL: ["La Paz", "Santa Cruz de la Sierra", "Sucre"],
  BRA: ["Sao Paulo", "Rio de Janeiro", "Brasilia", "Salvador"],
  BRN: ["Bandar Seri Begawan", "Kuala Belait"],
  BTN: ["Thimphu", "Paro"],
  BWA: ["Gaborone", "Maun"],
  CAN: ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa"],
  CHE: ["Zurich", "Geneva", "Bern", "Basel"],
  CHL: ["Santiago", "Valparaiso", "Punta Arenas"],
  CHN: ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu", "Hong Kong"],
  COL: ["Bogota", "Medellin", "Cartagena", "Cali"],
  CRI: ["San Jose", "Liberia", "Limon"],
  CYP: ["Nicosia", "Limassol", "Paphos"],
  CZE: ["Prague", "Brno", "Ostrava"],
  DEU: ["Berlin", "Munich", "Frankfurt", "Hamburg", "Cologne"],
  DNK: ["Copenhagen", "Aarhus", "Odense"],
  DOM: ["Santo Domingo", "Punta Cana", "Santiago de los Caballeros"],
  DZA: ["Algiers", "Oran", "Constantine"],
  ECU: ["Quito", "Guayaquil", "Cuenca"],
  EGY: ["Cairo", "Alexandria", "Luxor", "Sharm El Sheikh"],
  ESP: ["Madrid", "Barcelona", "Seville", "Valencia", "Bilbao"],
  EST: ["Tallinn", "Tartu", "Parnu"],
  FIN: ["Helsinki", "Rovaniemi", "Turku"],
  FJI: ["Suva", "Nadi", "Lautoka"],
  FRA: ["Paris", "Nice", "Lyon", "Marseille", "Bordeaux"],
  GBR: ["London", "Edinburgh", "Manchester", "Liverpool", "Bristol"],
  GEO: ["Tbilisi", "Batumi", "Kutaisi"],
  GHA: ["Accra", "Kumasi", "Tamale"],
  GRC: ["Athens", "Thessaloniki", "Heraklion"],
  HKG: ["Hong Kong", "Kowloon", "Sha Tin"],
  HRV: ["Zagreb", "Split", "Dubrovnik"],
  HUN: ["Budapest", "Debrecen", "Szeged"],
  IDN: ["Jakarta", "Bali", "Surabaya", "Yogyakarta"],
  IND: ["New Delhi", "Mumbai", "Bengaluru", "Kolkata", "Chennai"],
  IRL: ["Dublin", "Cork", "Galway"],
  IRN: ["Tehran", "Isfahan", "Shiraz"],
  ISL: ["Reykjavik", "Akureyri", "Keflavik"],
  ISR: ["Tel Aviv", "Jerusalem", "Haifa"],
  ITA: ["Rome", "Milan", "Venice", "Florence", "Naples"],
  JOR: ["Amman", "Aqaba", "Irbid"],
  JPN: ["Tokyo", "Osaka", "Kyoto", "Sapporo", "Fukuoka"],
  KEN: ["Nairobi", "Mombasa", "Kisumu"],
  KHM: ["Phnom Penh", "Siem Reap", "Sihanoukville"],
  KOR: ["Seoul", "Busan", "Jeju", "Incheon"],
  KWT: ["Kuwait City", "Al Ahmadi"],
  LAO: ["Vientiane", "Luang Prabang", "Pakse"],
  LBN: ["Beirut", "Tripoli", "Byblos"],
  LKA: ["Colombo", "Kandy", "Galle"],
  LTU: ["Vilnius", "Kaunas", "Klaipeda"],
  LUX: ["Luxembourg City", "Esch-sur-Alzette"],
  LVA: ["Riga", "Daugavpils", "Jurmala"],
  MAR: ["Rabat", "Marrakesh", "Casablanca", "Fez"],
  MEX: ["Mexico City", "Cancun", "Guadalajara", "Monterrey"],
  MMR: ["Yangon", "Mandalay", "Naypyidaw"],
  MNG: ["Ulaanbaatar", "Erdenet"],
  MUS: ["Port Louis", "Grand Baie"],
  MYS: ["Kuala Lumpur", "Penang", "Johor Bahru", "Kota Kinabalu"],
  NGA: ["Lagos", "Abuja", "Port Harcourt"],
  NLD: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht"],
  NOR: ["Oslo", "Bergen", "Tromso", "Stavanger"],
  NZL: ["Auckland", "Wellington", "Christchurch", "Queenstown"],
  OMN: ["Muscat", "Salalah", "Nizwa"],
  PAK: ["Islamabad", "Lahore", "Karachi", "Peshawar"],
  PAN: ["Panama City", "Colon", "David"],
  PER: ["Lima", "Cusco", "Arequipa", "Iquitos"],
  PHL: ["Manila", "Cebu", "Davao", "Boracay"],
  POL: ["Warsaw", "Krakow", "Gdansk", "Wroclaw"],
  PRT: ["Lisbon", "Porto", "Funchal", "Faro"],
  QAT: ["Doha", "Al Wakrah"],
  ROU: ["Bucharest", "Cluj-Napoca", "Brasov"],
  RUS: ["Moscow", "Saint Petersburg", "Sochi", "Kazan"],
  SAU: ["Riyadh", "Jeddah", "Mecca", "Medina"],
  SGP: ["Singapore"],
  SRB: ["Belgrade", "Novi Sad", "Nis"],
  SWE: ["Stockholm", "Gothenburg", "Malmo", "Kiruna"],
  THA: ["Bangkok", "Chiang Mai", "Phuket", "Pattaya"],
  TUN: ["Tunis", "Sousse", "Djerba"],
  TUR: ["Istanbul", "Ankara", "Izmir", "Antalya", "Cappadocia"],
  TWN: ["Taipei", "Kaohsiung", "Taichung", "Tainan"],
  UKR: ["Kyiv", "Lviv", "Odesa"],
  USA: ["New York", "Los Angeles", "San Francisco", "Chicago", "Miami"],
  UZB: ["Tashkent", "Samarkand", "Bukhara"],
  VAT: ["Vatican City"],
  VNM: ["Hanoi", "Ho Chi Minh City", "Da Nang", "Hoi An"],
  ZAF: ["Cape Town", "Johannesburg", "Durban", "Pretoria"],
};

export function getCities(country: CountryProfile): string[] {
  const choices = cityMap[country.iso3];
  return choices?.length ? choices : [country.name];
}
